"""
daemon/builder.py — evez-agentnet
Self-building layer: reads own source, generates patches via LLM,
opens PRs automatically.
Resolves: evez-agentnet#15

Triggered when a daemon-task issue title starts with [BUILD].

Env:
  GITHUB_TOKEN, OPENROUTER_API_KEY, DAEMON_REPO
"""
import os
import json
import base64
import logging
import urllib.request
from typing import Optional
from daemon import router

log = logging.getLogger("daemon.builder")

TOKEN = os.environ.get("GITHUB_TOKEN", "")
REPO  = os.environ.get("DAEMON_REPO", "EvezArt/evez-agentnet")
API   = "https://api.github.com"

HEADERS = {
    "Authorization": f"Bearer {TOKEN}",
    "Accept": "application/vnd.github+json",
    "Content-Type": "application/json",
    "X-GitHub-Api-Version": "2022-11-28",
}


def _gh(method, path, body=None):
    url  = f"{API}{path}"
    data = json.dumps(body).encode() if body else None
    req  = urllib.request.Request(url, data=data, headers=HEADERS, method=method)
    try:
        with urllib.request.urlopen(req, timeout=15) as r:
            return json.loads(r.read())
    except Exception as e:
        return {"error": str(e)}


def handle_build_task(issue_number: int, title: str, body: str) -> str:
    """
    Called when issue title starts with [BUILD].
    Uses LLM to generate a code patch, then opens a PR.
    Returns summary string for issue comment.
    """
    log.info(f"[builder] Handling BUILD task #{issue_number}: {title}")

    system = (
        "You are an expert Python developer working on the evez-agentnet project. "
        "Your job is to generate minimal, working code patches based on task descriptions. "
        "Output ONLY the file content with no explanation. Start directly with the code."
    )
    prompt = (
        f"Task: {title}\n\nDetails:\n{body}\n\n"
        "Generate a Python implementation. "
        "Return only the complete file content."
    )

    code = router.complete(prompt, system=system, max_tokens=2048)
    if not code:
        return "LLM returned no output. Task requires manual implementation."

    # Derive filename from issue title
    slug = title.replace("[BUILD]", "").strip().lower()
    slug = "".join(c if c.isalnum() else "_" for c in slug).strip("_")[:40]
    filename = f"daemon/generated/{slug}.py"

    branch = f"daemon/build-{issue_number}-{slug[:20]}"
    pr_url = _create_pr(branch, filename, code, title, issue_number)
    if pr_url:
        return f"✅ PR opened: {pr_url}\nFile: `{filename}`"
    return f"Code generated but PR creation failed. Code preview:\n```python\n{code[:500]}\n```"


def _get_main_sha() -> Optional[str]:
    data = _gh("GET", f"/repos/{REPO}/git/refs/heads/main")
    return data.get("object", {}).get("sha")


def _create_pr(branch: str, filename: str, content: str,
               title: str, issue_number: int) -> Optional[str]:
    main_sha = _get_main_sha()
    if not main_sha:
        return None

    # Create branch
    _gh("POST", f"/repos/{REPO}/git/refs",
        {"ref": f"refs/heads/{branch}", "sha": main_sha})

    # Create file on branch
    encoded = base64.b64encode(content.encode()).decode()
    _gh("PUT", f"/repos/{REPO}/contents/{filename}", {
        "message": f"daemon: auto-generate {filename} (closes #{issue_number})",
        "content": encoded,
        "branch":  branch,
    })

    # Open PR
    pr = _gh("POST", f"/repos/{REPO}/pulls", {
        "title": f"[DAEMON] {title}",
        "head":  branch,
        "base":  "main",
        "body":  f"Auto-generated by daemon builder.\nCloses #{issue_number}.",
    })
    return pr.get("html_url")
