"""
EVEZ-OS Cross-Service Integration for disclosure.tools
Connects disclosure to ClawBreak, VCL, Observatory, World Solver, and AI Search.
Real value acceleration: one analysis triggers insights across the whole stack.
"""
import os
import json
import time
import asyncio
from typing import List, Dict, Optional, Tuple
from dataclasses import dataclass, field
import httpx


# EVEZ-OS service URLs
SERVICES = {
    "clawbreak": "http://127.0.0.1:8080",
    "vcl": "http://127.0.0.1:8081",
    "health_agg": "http://127.0.0.1:8085",
    "disclosure": "http://127.0.0.1:8087",
    "hunger": "http://127.0.0.1:8092",
    "energy": "http://127.0.0.1:8093",
    "health_solver": "http://127.0.0.1:8094",
    "education": "http://127.0.0.1:8095",
    "world_solver": "http://127.0.0.1:8096",
    "observatory": "http://127.0.0.1:8097",
}

# Search gateway (AI Search Exploitation System)
SEARCH_GATEWAY = os.environ.get("SEARCH_GATEWAY_URL", "http://127.0.0.1:8100")


@dataclass
class ServiceHealth:
    name: str
    url: str
    status: str = "unknown"
    version: str = ""
    response_ms: int = 0
    last_check: int = 0


@dataclass
class CrossServiceInsight:
    """An insight generated by correlating data across EVEZ-OS services."""
    id: str
    source_services: List[str]
    insight_type: str
    description: str
    confidence: float
    data: Dict = field(default_factory=dict)
    timestamp: int = 0

    def to_dict(self) -> Dict:
        return {
            "id": self.id,
            "source_services": self.source_services,
            "insight_type": self.insight_type,
            "description": self.description,
            "confidence": round(self.confidence, 4),
            "data": self.data,
            "timestamp": self.timestamp,
        }


class EVEZIntegration:
    """Cross-service integration hub for disclosure.tools."""

    def __init__(self):
        self.client = httpx.AsyncClient(timeout=15)
        self.service_health: Dict[str, ServiceHealth] = {}

    async def check_all_services(self) -> Dict[str, Dict]:
        """Health-check every EVEZ-OS service."""
        results = {}
        for name, url in SERVICES.items():
            try:
                start = time.time()
                resp = await self.client.get(f"{url}/health")
                elapsed = int((time.time() - start) * 1000)
                data = resp.json() if resp.status_code == 200 else {}
                health = ServiceHealth(
                    name=name, url=url, status="online",
                    version=data.get("version", "unknown"),
                    response_ms=elapsed,
                    last_check=int(time.time()),
                )
                results[name] = {
                    "status": "online",
                    "version": health.version,
                    "response_ms": elapsed,
                }
            except Exception:
                results[name] = {
                    "status": "offline",
                    "version": "",
                    "response_ms": 0,
                }
                health = ServiceHealth(name=name, url=url, status="offline")

            self.service_health[name] = health

        return results

    async def analyze_with_observatory(self, gap_report: Dict) -> Optional[Dict]:
        """Send gap findings to Observatory for consciousness event correlation."""
        try:
            resp = await self.client.post(
                f"{SERVICES['observatory']}/api/v1/event",
                json={
                    "type": "gap_detected",
                    "source": "disclosure.tools",
                    "data": {
                        "phi": gap_report.get("phi", 0),
                        "eta_star": gap_report.get("eta_star", 0),
                        "negative_eigenvalues": gap_report.get("negative_eigenvalues", 0),
                        "findings_count": len(gap_report.get("findings", [])),
                    },
                },
            )
            if resp.status_code == 200:
                return resp.json()
        except Exception:
            pass
        return None

    async def analyze_with_world_solver(self, gap_report: Dict) -> Optional[Dict]:
        """Send gap patterns to World Solver for eigenvalue correlation with global systems."""
        try:
            resp = await self.client.post(
                f"{SERVICES['world_solver']}/api/v1/correlate",
                json={
                    "source": "disclosure.tools",
                    "eigenvalues": gap_report.get("eigenvalues", []),
                    "phi": gap_report.get("phi", 0),
                    "eta_star": gap_report.get("eta_star", 0),
                    "category": "information_asymmetry",
                },
            )
            if resp.status_code == 200:
                return resp.json()
        except Exception:
            pass
        return None

    async def analyze_with_hunger(self, gap_report: Dict) -> Optional[Dict]:
        """Cross-reference gap patterns with hunger eigenvalue model.
        Core thesis: information hunger (censorship/secrecy) is a form of the dominant
        negative eigenvalue. Structural gaps in FOIA = structural hunger for truth."""
        try:
            resp = await self.client.post(
                f"{SERVICES['hunger']}/api/v1/correlate",
                json={
                    "source": "disclosure.tools",
                    "gap_score": gap_report.get("eta_star", 0),
                    "dominant_negative": gap_report.get("dominant_negative", 0),
                    "category": "information_hunger",
                    "description": "FOIA structural gaps mapped to hunger eigenvalue",
                },
            )
            if resp.status_code == 200:
                return resp.json()
        except Exception:
            pass
        return None

    async def generate_cross_insights(self, gap_report: Dict) -> List[CrossServiceInsight]:
        """Generate insights by correlating gap analysis with other EVEZ-OS services."""
        insights = []
        ts = int(time.time())

        # 1. Correlate with Observatory (consciousness at criticality)
        obs_result = await self.analyze_with_observatory(gap_report)
        if obs_result:
            insights.append(CrossServiceInsight(
                id=f"INS-{str(hash(str(ts)))[:8].upper()}",
                source_services=["disclosure", "observatory"],
                insight_type="consciousness_correlation",
                description=f"Gap analysis Φ={gap_report.get('phi',0)} correlates with consciousness state",
                confidence=min(1.0, abs(gap_report.get("eta_star", 0)) * 2),
                data={"observatory": obs_result},
                timestamp=ts,
            ))

        # 2. Correlate with World Solver (systemic eigenvalue patterns)
        world_result = await self.analyze_with_world_solver(gap_report)
        if world_result:
            insights.append(CrossServiceInsight(
                id=f"INS-{str(hash(str(ts+1)))[:8].upper()}",
                source_services=["disclosure", "world_solver"],
                insight_type="systemic_correlation",
                description="FOIA gap eigenvalues correlate with global information asymmetry",
                confidence=min(1.0, abs(gap_report.get("dominant_negative", 0)) * 3),
                data={"world_solver": world_result},
                timestamp=ts,
            ))

        # 3. Correlate with Hunger (information hunger = censorship hunger)
        hunger_result = await self.analyze_with_hunger(gap_report)
        if hunger_result:
            insights.append(CrossServiceInsight(
                id=f"INS-{str(hash(str(ts+2)))[:8].upper()}",
                source_services=["disclosure", "hunger"],
                insight_type="hunger_correlation",
                description="Structural FOIA gaps map to information hunger eigenvalue — secrecy IS hunger",
                confidence=min(1.0, abs(gap_report.get("dominant_negative", 0)) * 4),
                data={"hunger": hunger_result},
                timestamp=ts,
            ))

        # 4. Always generate the thesis insight (even if services are down)
        eta_star = gap_report.get("eta_star", 0)
        if eta_star > 0.3:
            insights.append(CrossServiceInsight(
                id=f"INS-{str(hash(str(ts+3)))[:8].upper()}",
                source_services=["disclosure", "hunger", "world_solver"],
                insight_type="dominant_negative_eigenvalue",
                description=(
                    f"η*={eta_star:.4f}: FOIA corpus is {(eta_star*100):.0f}% structurally incomplete. "
                    f"The dominant negative eigenvalue ({gap_report.get('dominant_negative',0):.4f}) "
                    f"represents information hunger — the same force that drives physical hunger "
                    f"at civilization scale. Censorship is hunger. Secrecy is starvation."
                ),
                confidence=min(1.0, eta_star * 2),
                data={"eta_star": eta_star, "thesis": "hunger_is_dominant_negative"},
                timestamp=ts,
            ))

        return insights

    async def search_for_gaps(self, query: str) -> List[Dict]:
        """Use AI Search to find documents that might fill detected gaps."""
        try:
            resp = await self.client.post(
                f"{SEARCH_GATEWAY}/api/v1/search",
                json={"query": query, "max_results": 10},
            )
            if resp.status_code == 200:
                return resp.json().get("results", [])
        except Exception:
            pass

        # Fallback: direct web search operators
        from ai_search_integration import UAP_SEARCH_OPERATORS
        operator = UAP_SEARCH_OPERATORS.get(query, query)
        return [{"query": operator, "status": "search_pending", "operator": query}]

    async def close(self):
        await self.client.aclose()


# Singleton
evez_integration = EVEZIntegration()
