#!/usr/bin/env python3
"""
Skill Synthesizer — creates new skills from learned knowledge.
Combines discoveries with existing codebase capabilities to generate
new agent skills. Each skill follows the OpenClaw format: SKILL.md + implementation.
Stores synthesized skills in skills/generated/ and can create PRs.
"""
import os
import json
import logging
import urllib.request
import urllib.error
from datetime import datetime, timezone
from pathlib import Path

log = logging.getLogger("agentnet.knowledge.skill_synth")

GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "")
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
OWNER = "EvezArt"

DISCOVERIES_DIR = Path("knowledge/discoveries")
GRAPH_PATH = Path("knowledge/graph.json")
SKILLS_DIR = Path("skills/generated")
SKILLS_DIR.mkdir(parents=True, exist_ok=True)


def now_iso():
    return datetime.now(timezone.utc).isoformat()


def _call_groq(prompt: str) -> str:
    """Call Groq for AI-powered skill synthesis."""
    if not GROQ_API_KEY:
        return ""
    try:
        body = json.dumps({
            "model": "llama-3.3-70b-versatile",
            "messages": [{"role": "user", "content": prompt}],
            "max_tokens": 1024,
            "temperature": 0.4,
        }).encode()
        req = urllib.request.Request(
            "https://api.groq.com/openai/v1/chat/completions",
            data=body,
            headers={
                "Authorization": f"Bearer {GROQ_API_KEY}",
                "Content-Type": "application/json",
            },
        )
        with urllib.request.urlopen(req, timeout=25) as resp:
            data = json.loads(resp.read())
        return data["choices"][0]["message"]["content"]
    except Exception as e:
        log.warning(f"Groq synthesis failed: {e}")
        return ""


def _load_high_relevance_discoveries(min_score: float = 0.5) -> list:
    """Load discoveries above relevance threshold."""
    discoveries = []
    if not DISCOVERIES_DIR.exists():
        return discoveries
    for fpath in sorted(DISCOVERIES_DIR.glob("*.json")):
        try:
            d = json.loads(fpath.read_text())
            if d.get("relevance_score", 0) >= min_score:
                discoveries.append(d)
        except Exception:
            pass
    return discoveries


def _load_knowledge_graph() -> dict:
    if GRAPH_PATH.exists():
        return json.loads(GRAPH_PATH.read_text())
    return {"concepts": {}}


def _find_skill_opportunities(discoveries: list, graph: dict) -> list:
    """Identify opportunities for new skills from discoveries + knowledge graph."""
    opportunities = []

    # Group discoveries by concept clusters
    concept_clusters = {}
    for concept, data in graph.get("concepts", {}).items():
        if len(data.get("discoveries", [])) >= 2:
            concept_clusters[concept] = data

    # Discoveries with high applicability
    for d in discoveries:
        applicability = d.get("applicability", "")
        if "enhance" in applicability.lower() or "improve" in applicability.lower():
            opportunities.append({
                "type": "enhancement",
                "discovery": d,
                "concept": d["title"][:50],
                "reason": applicability,
            })

    # Cross-concept opportunities from graph
    for concept, data in concept_clusters.items():
        repos = data.get("repos", [])
        if len(repos) >= 2:
            opportunities.append({
                "type": "cross_repo",
                "concept": concept,
                "repos": repos,
                "discovery_count": len(data.get("discoveries", [])),
                "reason": f"Pattern '{concept}' appears across {', '.join(repos)} — skill could unify approach",
            })

    return opportunities[:10]  # Cap at 10 per run


def _generate_skill_manifest(name: str, description: str, triggers: list) -> str:
    """Generate SKILL.md manifest in OpenClaw format."""
    trigger_lines = "\n".join(f"- {t}" for t in triggers)
    return f"""---
name: {name}
description: {description}
type: generated
created_at: {now_iso()}
status: draft
---

# {name}

{description}

## Triggers

{trigger_lines}

## Usage

This skill was auto-generated by the EVEZ knowledge expansion system.
It requires human review before activation.

## Source

Generated from knowledge discoveries by skill_synth.py
"""


def _generate_skill_implementation(opportunity: dict) -> str:
    """Generate a Python skill implementation from an opportunity."""
    prompt = f"""You are generating a Python module for an autonomous agent skill.

Opportunity: {json.dumps(opportunity, default=str)}

Generate a simple, fault-tolerant Python module that:
1. Has a run() function as the main entry point
2. Uses only stdlib + requests
3. Handles missing env vars gracefully
4. Returns a dict with results
5. Is under 80 lines

Output ONLY the Python code, no markdown fences."""

    code = _call_groq(prompt)
    if not code:
        # Fallback template
        name = opportunity.get("concept", "unknown").replace(" ", "_").lower()
        code = f'''#!/usr/bin/env python3
"""Auto-generated skill: {name}
Source: Knowledge expansion system
Status: Draft — requires human review
"""
import json
import logging
from datetime import datetime, timezone

log = logging.getLogger("agentnet.skill.{name}")


def run(**kwargs) -> dict:
    """Execute the {name} skill."""
    log.info("Skill {name} executing...")
    return {{
        "skill": "{name}",
        "status": "draft",
        "message": "This skill requires implementation. See knowledge/discoveries/ for source material.",
        "executed_at": datetime.now(timezone.utc).isoformat(),
    }}


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    print(json.dumps(run(), indent=2))
'''
    return code


def _save_skill(name: str, manifest: str, implementation: str) -> str:
    """Save a generated skill to skills/generated/."""
    skill_dir = SKILLS_DIR / name
    skill_dir.mkdir(parents=True, exist_ok=True)

    (skill_dir / "SKILL.md").write_text(manifest)
    (skill_dir / f"{name}.py").write_text(implementation)

    # Track metadata
    meta = {
        "name": name,
        "created_at": now_iso(),
        "status": "draft",
        "requires_review": True,
    }
    (skill_dir / "meta.json").write_text(json.dumps(meta, indent=2))

    return str(skill_dir)


def run() -> dict:
    """Synthesize new skills from knowledge discoveries."""
    log.info(f"Skill Synthesizer starting — {now_iso()}")

    discoveries = _load_high_relevance_discoveries(min_score=0.4)
    graph = _load_knowledge_graph()
    opportunities = _find_skill_opportunities(discoveries, graph)

    stats = {"opportunities_found": len(opportunities), "skills_generated": 0, "skills": []}

    for opp in opportunities[:5]:  # Max 5 skills per run
        concept = opp.get("concept", "unknown")
        name = concept.replace(" ", "_").replace("-", "_").lower()[:30]
        # Sanitize name
        name = "".join(c for c in name if c.isalnum() or c == "_")
        if not name:
            continue

        description = opp.get("reason", f"Skill derived from {concept}")
        triggers = [
            f"When working with {concept}",
            "When knowledge expansion identifies relevant patterns",
        ]

        manifest = _generate_skill_manifest(name, description, triggers)
        implementation = _generate_skill_implementation(opp)

        path = _save_skill(name, manifest, implementation)
        stats["skills_generated"] += 1
        stats["skills"].append({"name": name, "path": path, "type": opp["type"]})
        log.info(f"  Generated skill: {name} ({opp['type']})")

    log.info(f"  Stats: {stats['skills_generated']} skills generated from {stats['opportunities_found']} opportunities")
    return stats


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    stats = run()
    print(json.dumps(stats, indent=2))
