#!/usr/bin/env python3
"""
evez-agentnet/generator/generate_agent.py
Draft deliverables from ranked predictions.
Output types: twitter_thread, gumroad_report, gumroad_product, github_post.
"""

import os, json, logging
from pathlib import Path
from datetime import datetime, timezone

log = logging.getLogger("agentnet.generator")
GROQ_KEY = os.environ.get("GROQ_API_KEY", "")
DRAFTS_DIR = Path("drafts")
DRAFTS_DIR.mkdir(exist_ok=True)


def run(predictions: list, truth_plane: str = "CANONICAL") -> list:
    """Generate drafts for top predictions. Gates on truth_plane."""
    drafts = []
    for pred in predictions[:3]:  # max 3 drafts per round
        try:
            draft = _generate_draft(pred, truth_plane)
            if draft:
                drafts.append(draft)
        except Exception as e:
            log.error(f"Draft failed for {pred.get('title', '?')}: {e}")
    return drafts


def _generate_draft(pred: dict, truth_plane: str) -> dict | None:
    dtype = pred.get("deliverable_type", "twitter_thread")
    title = pred.get("title", "Untitled")
    plan = pred.get("action_plan", "")

    if dtype == "twitter_thread":
        content = _gen_tweet_thread(title, plan)
    elif dtype in ("gumroad_report", "gumroad_product"):
        content = _gen_gumroad_product(title, plan)
    elif dtype == "github_post":
        content = _gen_github_readme(title, plan)
    else:
        content = _gen_tweet_thread(title, plan)

    if not content:
        return None

    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    fname = f"{dtype}_{ts}.json"
    draft = {
        "type": dtype, "title": title, "content": content,
        "truth_plane": truth_plane, "created_at": datetime.now(timezone.utc).isoformat(),
        "source_signal": pred.get("source", ""), "opportunity_score": pred.get("opportunity_score", 0),
        "file": str(DRAFTS_DIR / fname),
    }
    (DRAFTS_DIR / fname).write_text(json.dumps(draft, indent=2))
    log.info(f"  Draft: {dtype} -- {title[:50]}")
    return draft


def _gen_tweet_thread(title: str, plan: str) -> str:
    """Generate a 5-tweet thread."""
    if GROQ_KEY:
        try:
            return _groq_gen(f"Write a 5-tweet numbered thread about: {title}\nPlan: {plan}\nStyle: EVEZ666 -- technical, direct, no fluff. Include EVEZ-OS angle.", max_tokens=400)
        except:
            pass
    # Fallback template
    return f"""1/ {title} -- here's what matters.

2/ The signal: {plan[:100]}

3/ EVEZ-OS is scanning, predicting, and generating content from live market signals autonomously.

4/ Built on formal Bayesian proofs. R36: self_governance_engine -- policy over policies. github.com/EvezArt/evez-os

5/ If you want the full synthesis: rubikspubes.gumroad.com -- prediction reports, CTF challenges, cognitive toolkits."""


def _gen_gumroad_product(title: str, plan: str) -> str:
    """Generate a Gumroad product description + pricing."""
    if GROQ_KEY:
        try:
            return _groq_gen(f"Write a Gumroad product description for: {title}\nPlan: {plan}\nFormat: 2-3 paragraphs, bullet list of what's included, price recommendation $9-29.", max_tokens=300)
        except:
            pass
    return f"""# {title}

{plan}

**What's included:**
- Full analysis report (PDF + Markdown)
- Data sources and methodology
- EVEZ-OS synthesis (formal Bayesian framework)
- Action recommendations

**Price: $19** (pay what you want above minimum)

Generated by EVEZ-OS autonomous agent swarm -- Steven Crawford-Maggard (EVEZ666)"""


def _gen_github_readme(title: str, plan: str) -> str:
    return f"# {title}\n\n{plan}\n\nGenerated by EVEZ-OS. Creator: Steven Crawford-Maggard (EVEZ666)"


def _groq_gen(prompt: str, max_tokens: int = 300) -> str:
    import urllib.request, urllib.error
    payload = {
        "model": "llama-3.3-70b-versatile",
        "messages": [
            {"role": "system", "content": "You are EVEZ666, creator of EVEZ-OS. Write direct, technical, no-BS content."},
            {"role": "user", "content": prompt}
        ],
        "max_tokens": max_tokens, "temperature": 0.5,
    }
    req = urllib.request.Request(
        "https://api.groq.com/openai/v1/chat/completions",
        data=json.dumps(payload).encode(),
        headers={"Authorization": f"Bearer {GROQ_KEY}", "Content-Type": "application/json"}
    )
    with urllib.request.urlopen(req, timeout=20) as r:
        resp = json.loads(r.read())
    return resp["choices"][0]["message"]["content"].strip()
